### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by ranhsd** [regexident/Gestalt#12]
Hi, thanks for this great library! 

Cocoapods currently point to earlier version (1.1.0) 
can you please update it to point to the latest one (2.0) ? 

https://cocoapods.org/pods/Gestalt

Thanks!

**Comment by regexident** [comment]
Hi Ran,

I'm aware of the issue, however don't have the time right now to fix it.

`$ pod lib lint` keeps on failing for some reason:

```
 -> Gestalt (2.0.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

[!] Gestalt did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
```

Running it with `--verbose` this line shows up as possible culprit:

```
…/Pods-App-frameworks.sh: line 104: EXPANDED_CODE_SIGN_IDENTITY: unbound variable
    Command PhaseScriptExecution failed with a nonzero exit code
```

I'm far too busy to investigate things myself right now, unfortunately,
but I'd be more than happy to merge a PR fixing it!

**Comment by ilessiivi** [comment]
I'm hoping to test this library soon for a project and I'd strongly prefer Cocoapods as the installation method.

`$ pod lib lint` fails due to an issue in the current version of Cocoapods: https://github.com/CocoaPods/CocoaPods/issues/7708

There's a beta version of Cocoapods available with a fix applied. I tried linting Gestalt myself on Cocoapods 1.6.0 beta 2 and it passes, so no code changes are necessary. We'll just have to wait for the 1.6 release (there's no release date set though), or use the beta.

**Comment by regexident** [comment]
Thanks for the explanation, @ilessiivi! I'm using Carthage over CocoaPods any time I can, so wasn't familiar with the errors being produced.

I just pushed v2.0: https://cocoapods.org/pods/Gestalt
