### ISSUE TITLE
Changing appearance causes broken keyboard/toolbar

### ISSUE THREAD

**Issue by patrickniepel** [regexident/Gestalt#25]
Hi there,

there is a strange thing going on with the keyboard / toolbar when switching the theme which is apparently caused by this "hack" in `ThemeManager` https://github.com/regexident/Gestalt/blob/master/Gestalt/ThemeManager.swift#L259

It causes the toolbar to "detach" from the keyboard and slide in and out from the top of the screen. I assume the keyboard view itself breaks when being removed and added again afterwards.

Do you know if there is a better way to change the appearance or is this still the only possible "solution"?

Thanks in advance :) 

It's a bit hard to see on the screenshot but I also included the sample project.
<img width="587" alt="Bildschirmfoto 2020-12-09 um 14 53 18" src="https://user-images.githubusercontent.com/22814132/101638614-92c19980-3a2e-11eb-9160-e12c16c2ae63.png">

Sample project:
[BrokenKeyboard.zip](https://github.com/regexident/Gestalt/files/5666279/BrokenKeyboard.zip)

**Comment by regexident** [comment]
Hi Patrick,

Thanks for taking the time to prepare a sample project!
Unfortunately I am not aware of any other way to accomplish this behavior.

**Comment by EmDee** [comment]
Hi @regexident,

I just had a quick look and the problem occurs, because during the window traversal, the views in the `UITextEffectsWindow` are also removed, which will then mess up the keyboard.

One potential "hack for the hack part" would be to ignore that class:

```swift
for window in windowScene.windows.reversed() {
    if NSStringFromClass(window.classForCoder) == "UITextEffectsWindow" {
        NSLog("===== Ignore UITextEffectsWindow")
        return
     }

    for view in window.subviews.reversed() {
        view.removeFromSuperview()
        window.addSubview(view)
    }
}
```

Is that something you would consider adding to your code? If yes, I can open up a merge request.

I'm currently unsure, if using this check is already considered private API usage. I've pinged an Apple DTS engineer and am awaiting an answer.

**Comment by EmDee** [comment]
Of course we could also do the reverse and only remove the views in case the window is in fact a `UIWindow`.

**Comment by EmDee** [comment]
@regexident I've added a sample implementation of how I would imagine a possible fix, I tried it out and it works for our use cases: https://github.com/regexident/Gestalt/pull/26
